/* eslint-disable */
// @ts-nocheck
/* originally generated by NAPI-RS, now tracked and edited by hand */

const { readFileSync, readdirSync } = require('fs')

// Verbose load tracing
// --------------------
//
// Everything below, up to the end of this section, is hand-written; the
// rest of this file is the loader NAPI-RS generates. The builder passes
// `--js index-generated.js` so that a NAPI build writes its loader beside
// this one rather than over it, leaving `index-generated.js` as the
// reference to re-derive this file from when a NAPI-RS upgrade changes
// what it emits.
//
// A binding which fails to load reaches the user as a single
// "Cannot find native binding" thrown during extension activation, naming
// neither the artifact which was tried nor the reason each attempt failed.
// Every decision and every `require` attempt below is therefore logged, so
// that an Extension Host log copied from the user's machine identifies the
// failing step. Set `CODECHAT_NAPI_DEBUG=0` to silence the output.
const __dbgEnabled = process.env.CODECHAT_NAPI_DEBUG !== '0'
const __dbg = (...args) => {
  if (!__dbgEnabled) return
  try {
    console.log('[codechat-napi]', ...args)
  } catch {
    // A console which throws must not turn a working load into a failure.
  }
}
// Render an error as a single line. What arrives here is whatever a failed
// `require` produced, which includes non-Errors thrown by an addon's own
// initialization code.
const __dbgErrText = (e) => {
  try {
    if (e && typeof e === 'object') {
      return `${e.name || 'Error'}${e.code ? ' [' + e.code + ']' : ''}: ${e.message}`
    }
    return String(e)
  } catch {
    return '<unprintable error>'
  }
}
const __dbgStack = (e) => {
  try {
    return e && typeof e === 'object' && typeof e.stack === 'string' ? e.stack : ''
  } catch {
    return ''
  }
}
// An array whose `push` announces what it collects. The loader funnels every
// failed attempt into one of two such arrays, so tracing `push` reports each
// failure without touching the `require` call sites -- which must keep their
// literal string arguments for esbuild's `.node` copy loader to find them.
const __dbgTracedArray = (label) => {
  const array = []
  if (!__dbgEnabled) return array
  const push = Array.prototype.push.bind(array)
  array.push = (...items) => {
    for (const item of items) {
      __dbg(`${label} <- ${__dbgErrText(item)}`)
      const stack = __dbgStack(item)
      if (stack) __dbg(`${label} <- stack: ${stack}`)
    }
    return push(...items)
  }
  return array
}
const __dbgAttempt = (kind, specifier) => {
  __dbg(`attempting ${kind}: ${specifier}`)
}
// Report a successful load, then hand the binding back, so that this wraps an
// existing expression instead of restructuring the block it sits in.
const __dbgOk = (specifier, binding) => {
  let keys
  try {
    keys = binding ? Object.keys(binding).join(', ') : String(binding)
  } catch (e) {
    keys = `<keys unavailable: ${__dbgErrText(e)}>`
  }
  __dbg(`LOADED ${specifier} -- exports: ${keys}`)
  return binding
}
const LF = String.fromCharCode(10)
const CR = String.fromCharCode(13)
const SPACE = ''
const NL_INDENT = LF + '      '
const __dbgChain = (label, errors) => {
  __dbg(`${label}: ${errors.length} error(s) recorded`)
  errors.forEach((e, i) => {
    __dbg(`  [${i}] ${__dbgErrText(e)}`)
    const stack = __dbgStack(e)
    // Indent a multi-line stack so that it reads as one entry in the log.
    if (stack) __dbg(NL_INDENT.slice(1) + stack.split(CR).join(SPACE).split(LF).join(NL_INDENT))
  })
}

__dbg('==== binding load starting ====')
__dbg(`platform=${process.platform} arch=${process.arch} node=${process.version} modules=${process.versions.modules} electron=${process.versions.electron || 'none'}`)
__dbg(`execPath=${process.execPath}`)
__dbg(`cwd=${process.cwd()}`)
__dbg(`__dirname=${typeof __dirname === 'string' ? __dirname : '<undefined>'}`)
__dbg(`config.variables: shlib_suffix=${process.config && process.config.variables ? process.config.variables.shlib_suffix : '<none>'} node_target_type=${process.config && process.config.variables ? process.config.variables.node_target_type : '<none>'}`)
for (const __dbgEnvName of [
  'NAPI_RS_NATIVE_LIBRARY_PATH',
  'NAPI_RS_FORCE_WASI',
  'NAPI_RS_WASI_FLAVOR',
  'NAPI_RS_ENFORCE_VERSION_CHECK',
]) {
  __dbg(`env ${__dbgEnvName}=${process.env[__dbgEnvName] === undefined ? '<unset>' : JSON.stringify(process.env[__dbgEnvName])}`)
}
// The artifact is looked for beside this file, so a listing of that directory
// shows directly whether the expected `.node` was packaged and installed.
try {
  const __dbgDir = typeof __dirname === 'string' ? __dirname : '.'
  const __dbgEntries = readdirSync(__dbgDir)
  __dbg(`contents of ${__dbgDir} (${__dbgEntries.length} entries): ${__dbgEntries.join(', ')}`)
} catch (e) {
  __dbg(`directory listing failed: ${__dbgErrText(e)}`)
}
let nativeBinding = null
// Which artifact actually loaded. The WASI fallback chain overwrites it with
// the flavor it resolved; the late native retry below leaves it alone because
// it only runs while no WASI candidate has been loaded.
let __napiLoadedBindingTarget = 'native'
const loadErrors = __dbgTracedArray('loadErrors')

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  __dbg(`isMusl() = ${musl}`)
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (process.report && typeof process.report.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  __dbg('requireNative(): walking the platform/arch chain')
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      __dbgAttempt('NAPI_RS_NATIVE_LIBRARY_PATH override', process.env.NAPI_RS_NATIVE_LIBRARY_PATH)
      const overrideBinding = __dbgOk(process.env.NAPI_RS_NATIVE_LIBRARY_PATH, require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH))
      // The override may be a generated WASI loader, which already reports its
      // own flavor. Adopt it: `module.exports` aliases this object, so claiming
      // 'native' would both misreport the artifact and overwrite the loader's
      // marker through the alias.
      __napiLoadedBindingTarget =
        overrideBinding && typeof overrideBinding.__napiBindingTarget === 'string'
          ? overrideBinding.__napiBindingTarget
          : 'native'
      return overrideBinding
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.android-arm64.node')
        return __dbgOk('./codechat-editor-client.android-arm64.node', require('./codechat-editor-client.android-arm64.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-android-arm64')
        const binding = require('codechat-editor-client-android-arm64')
        const bindingPackageVersion = require('codechat-editor-client-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-android-arm64', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.android-arm-eabi.node')
        return __dbgOk('./codechat-editor-client.android-arm-eabi.node', require('./codechat-editor-client.android-arm-eabi.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-android-arm-eabi')
        const binding = require('codechat-editor-client-android-arm-eabi')
        const bindingPackageVersion = require('codechat-editor-client-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-android-arm-eabi', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if ((process.config && process.config.variables && process.config.variables.shlib_suffix === 'dll.a') || (process.config && process.config.variables && process.config.variables.node_target_type === 'shared_library')) {
        try {
          __dbgAttempt('local artifact', './codechat-editor-client.win32-x64-gnu.node')
          return __dbgOk('./codechat-editor-client.win32-x64-gnu.node', require('./codechat-editor-client.win32-x64-gnu.node'))
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          __dbgAttempt('optional dependency package', 'codechat-editor-client-win32-x64-gnu')
          const binding = require('codechat-editor-client-win32-x64-gnu')
          const bindingPackageVersion = require('codechat-editor-client-win32-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return __dbgOk('codechat-editor-client-win32-x64-gnu', binding)
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          __dbgAttempt('local artifact', './codechat-editor-client.win32-x64-msvc.node')
          return __dbgOk('./codechat-editor-client.win32-x64-msvc.node', require('./codechat-editor-client.win32-x64-msvc.node'))
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          __dbgAttempt('optional dependency package', 'codechat-editor-client-win32-x64-msvc')
          const binding = require('codechat-editor-client-win32-x64-msvc')
          const bindingPackageVersion = require('codechat-editor-client-win32-x64-msvc/package.json').version
          if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return __dbgOk('codechat-editor-client-win32-x64-msvc', binding)
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ia32') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.win32-ia32-msvc.node')
        return __dbgOk('./codechat-editor-client.win32-ia32-msvc.node', require('./codechat-editor-client.win32-ia32-msvc.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-win32-ia32-msvc')
        const binding = require('codechat-editor-client-win32-ia32-msvc')
        const bindingPackageVersion = require('codechat-editor-client-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-win32-ia32-msvc', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.win32-arm64-msvc.node')
        return __dbgOk('./codechat-editor-client.win32-arm64-msvc.node', require('./codechat-editor-client.win32-arm64-msvc.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-win32-arm64-msvc')
        const binding = require('codechat-editor-client-win32-arm64-msvc')
        const bindingPackageVersion = require('codechat-editor-client-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-win32-arm64-msvc', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      __dbgAttempt('local artifact', './codechat-editor-client.darwin-universal.node')
      return __dbgOk('./codechat-editor-client.darwin-universal.node', require('./codechat-editor-client.darwin-universal.node'))
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      __dbgAttempt('optional dependency package', 'codechat-editor-client-darwin-universal')
      const binding = require('codechat-editor-client-darwin-universal')
      const bindingPackageVersion = require('codechat-editor-client-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return __dbgOk('codechat-editor-client-darwin-universal', binding)
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.darwin-x64.node')
        return __dbgOk('./codechat-editor-client.darwin-x64.node', require('./codechat-editor-client.darwin-x64.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-darwin-x64')
        const binding = require('codechat-editor-client-darwin-x64')
        const bindingPackageVersion = require('codechat-editor-client-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-darwin-x64', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.darwin-arm64.node')
        return __dbgOk('./codechat-editor-client.darwin-arm64.node', require('./codechat-editor-client.darwin-arm64.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-darwin-arm64')
        const binding = require('codechat-editor-client-darwin-arm64')
        const bindingPackageVersion = require('codechat-editor-client-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-darwin-arm64', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.freebsd-x64.node')
        return __dbgOk('./codechat-editor-client.freebsd-x64.node', require('./codechat-editor-client.freebsd-x64.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-freebsd-x64')
        const binding = require('codechat-editor-client-freebsd-x64')
        const bindingPackageVersion = require('codechat-editor-client-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-freebsd-x64', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.freebsd-arm64.node')
        return __dbgOk('./codechat-editor-client.freebsd-arm64.node', require('./codechat-editor-client.freebsd-arm64.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-freebsd-arm64')
        const binding = require('codechat-editor-client-freebsd-arm64')
        const bindingPackageVersion = require('codechat-editor-client-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-freebsd-arm64', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          __dbgAttempt('local artifact', './codechat-editor-client.linux-x64-musl.node')
          return __dbgOk('./codechat-editor-client.linux-x64-musl.node', require('./codechat-editor-client.linux-x64-musl.node'))
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          __dbgAttempt('optional dependency package', 'codechat-editor-client-linux-x64-musl')
          const binding = require('codechat-editor-client-linux-x64-musl')
          const bindingPackageVersion = require('codechat-editor-client-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return __dbgOk('codechat-editor-client-linux-x64-musl', binding)
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          __dbgAttempt('local artifact', './codechat-editor-client.linux-x64-gnu.node')
          return __dbgOk('./codechat-editor-client.linux-x64-gnu.node', require('./codechat-editor-client.linux-x64-gnu.node'))
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          __dbgAttempt('optional dependency package', 'codechat-editor-client-linux-x64-gnu')
          const binding = require('codechat-editor-client-linux-x64-gnu')
          const bindingPackageVersion = require('codechat-editor-client-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return __dbgOk('codechat-editor-client-linux-x64-gnu', binding)
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          __dbgAttempt('local artifact', './codechat-editor-client.linux-arm64-musl.node')
          return __dbgOk('./codechat-editor-client.linux-arm64-musl.node', require('./codechat-editor-client.linux-arm64-musl.node'))
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          __dbgAttempt('optional dependency package', 'codechat-editor-client-linux-arm64-musl')
          const binding = require('codechat-editor-client-linux-arm64-musl')
          const bindingPackageVersion = require('codechat-editor-client-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return __dbgOk('codechat-editor-client-linux-arm64-musl', binding)
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          __dbgAttempt('local artifact', './codechat-editor-client.linux-arm64-gnu.node')
          return __dbgOk('./codechat-editor-client.linux-arm64-gnu.node', require('./codechat-editor-client.linux-arm64-gnu.node'))
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          __dbgAttempt('optional dependency package', 'codechat-editor-client-linux-arm64-gnu')
          const binding = require('codechat-editor-client-linux-arm64-gnu')
          const bindingPackageVersion = require('codechat-editor-client-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return __dbgOk('codechat-editor-client-linux-arm64-gnu', binding)
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          __dbgAttempt('local artifact', './codechat-editor-client.linux-arm-musleabihf.node')
          return __dbgOk('./codechat-editor-client.linux-arm-musleabihf.node', require('./codechat-editor-client.linux-arm-musleabihf.node'))
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          __dbgAttempt('optional dependency package', 'codechat-editor-client-linux-arm-musleabihf')
          const binding = require('codechat-editor-client-linux-arm-musleabihf')
          const bindingPackageVersion = require('codechat-editor-client-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return __dbgOk('codechat-editor-client-linux-arm-musleabihf', binding)
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          __dbgAttempt('local artifact', './codechat-editor-client.linux-arm-gnueabihf.node')
          return __dbgOk('./codechat-editor-client.linux-arm-gnueabihf.node', require('./codechat-editor-client.linux-arm-gnueabihf.node'))
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          __dbgAttempt('optional dependency package', 'codechat-editor-client-linux-arm-gnueabihf')
          const binding = require('codechat-editor-client-linux-arm-gnueabihf')
          const bindingPackageVersion = require('codechat-editor-client-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return __dbgOk('codechat-editor-client-linux-arm-gnueabihf', binding)
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          __dbgAttempt('local artifact', './codechat-editor-client.linux-loong64-musl.node')
          return __dbgOk('./codechat-editor-client.linux-loong64-musl.node', require('./codechat-editor-client.linux-loong64-musl.node'))
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          __dbgAttempt('optional dependency package', 'codechat-editor-client-linux-loong64-musl')
          const binding = require('codechat-editor-client-linux-loong64-musl')
          const bindingPackageVersion = require('codechat-editor-client-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return __dbgOk('codechat-editor-client-linux-loong64-musl', binding)
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          __dbgAttempt('local artifact', './codechat-editor-client.linux-loong64-gnu.node')
          return __dbgOk('./codechat-editor-client.linux-loong64-gnu.node', require('./codechat-editor-client.linux-loong64-gnu.node'))
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          __dbgAttempt('optional dependency package', 'codechat-editor-client-linux-loong64-gnu')
          const binding = require('codechat-editor-client-linux-loong64-gnu')
          const bindingPackageVersion = require('codechat-editor-client-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return __dbgOk('codechat-editor-client-linux-loong64-gnu', binding)
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          __dbgAttempt('local artifact', './codechat-editor-client.linux-riscv64-musl.node')
          return __dbgOk('./codechat-editor-client.linux-riscv64-musl.node', require('./codechat-editor-client.linux-riscv64-musl.node'))
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          __dbgAttempt('optional dependency package', 'codechat-editor-client-linux-riscv64-musl')
          const binding = require('codechat-editor-client-linux-riscv64-musl')
          const bindingPackageVersion = require('codechat-editor-client-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return __dbgOk('codechat-editor-client-linux-riscv64-musl', binding)
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          __dbgAttempt('local artifact', './codechat-editor-client.linux-riscv64-gnu.node')
          return __dbgOk('./codechat-editor-client.linux-riscv64-gnu.node', require('./codechat-editor-client.linux-riscv64-gnu.node'))
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          __dbgAttempt('optional dependency package', 'codechat-editor-client-linux-riscv64-gnu')
          const binding = require('codechat-editor-client-linux-riscv64-gnu')
          const bindingPackageVersion = require('codechat-editor-client-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return __dbgOk('codechat-editor-client-linux-riscv64-gnu', binding)
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.linux-ppc64-gnu.node')
        return __dbgOk('./codechat-editor-client.linux-ppc64-gnu.node', require('./codechat-editor-client.linux-ppc64-gnu.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-linux-ppc64-gnu')
        const binding = require('codechat-editor-client-linux-ppc64-gnu')
        const bindingPackageVersion = require('codechat-editor-client-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-linux-ppc64-gnu', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.linux-s390x-gnu.node')
        return __dbgOk('./codechat-editor-client.linux-s390x-gnu.node', require('./codechat-editor-client.linux-s390x-gnu.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-linux-s390x-gnu')
        const binding = require('codechat-editor-client-linux-s390x-gnu')
        const bindingPackageVersion = require('codechat-editor-client-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-linux-s390x-gnu', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.openharmony-arm64.node')
        return __dbgOk('./codechat-editor-client.openharmony-arm64.node', require('./codechat-editor-client.openharmony-arm64.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-openharmony-arm64')
        const binding = require('codechat-editor-client-openharmony-arm64')
        const bindingPackageVersion = require('codechat-editor-client-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-openharmony-arm64', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.openharmony-x64.node')
        return __dbgOk('./codechat-editor-client.openharmony-x64.node', require('./codechat-editor-client.openharmony-x64.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-openharmony-x64')
        const binding = require('codechat-editor-client-openharmony-x64')
        const bindingPackageVersion = require('codechat-editor-client-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-openharmony-x64', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        __dbgAttempt('local artifact', './codechat-editor-client.openharmony-arm.node')
        return __dbgOk('./codechat-editor-client.openharmony-arm.node', require('./codechat-editor-client.openharmony-arm.node'))
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        __dbgAttempt('optional dependency package', 'codechat-editor-client-openharmony-arm')
        const binding = require('codechat-editor-client-openharmony-arm')
        const bindingPackageVersion = require('codechat-editor-client-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.2.5' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return __dbgOk('codechat-editor-client-openharmony-arm', binding)
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

function createLoadErrorChain(errors) {
  return errors.reduce((previous, current) => {
    let message
    try {
      message =
        current && typeof current.message === 'string'
          ? current.message
          : String(current)
    } catch {
      message = 'Unknown error'
    }
    const error = new Error(message)
    error.cause = previous
    return error
  }, null)
}

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → prefer WASI, but retain native as a lazy fallback
//   'error'                  → require WASI without initializing a native fallback
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
//
// NAPI_RS_WASI_FLAVOR selects one exact generated flavor and implies strict
// WASI loading. It never crosses into another flavor or falls back to native.
const __napiWasiFlavors = ['wasm32-wasi']
const __napiWasiFlavor = process.env.NAPI_RS_WASI_FLAVOR
const __napiWasiFlavorRequested =
  typeof __napiWasiFlavor === 'string' && __napiWasiFlavor.length > 0
if (
  __napiWasiFlavorRequested &&
  __napiWasiFlavors.indexOf(__napiWasiFlavor) === -1
) {
  throw new Error(
    'Unsupported WASI flavor "' +
      __napiWasiFlavor +
      '". Available flavors: ' +
      __napiWasiFlavors.join(', '),
  )
}
const forceWasiError = process.env.NAPI_RS_FORCE_WASI === 'error'
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' ||
  forceWasiError ||
  __napiWasiFlavorRequested

__dbg(
  `WASI selection: forceWasi=${forceWasi} forceWasiError=${forceWasiError} flavorRequested=${__napiWasiFlavorRequested} flavor=${__napiWasiFlavor || '<unset>'}`,
)
if (!forceWasi) {
  nativeBinding = requireNative()
  __dbg(`requireNative() returned ${nativeBinding ? 'a binding' : 'nothing'}`)
} else {
  __dbg('skipping the native chain: WASI was forced')
}

if (!nativeBinding || forceWasi) {
  __dbg('entering the WASI fallback chain')
  let wasiBinding = null
  let wasiBindingLoaded = false
  const wasiBindingErrors = __dbgTracedArray('wasiBindingErrors')
  const __napiWasiResolveCandidate = (specifier, isPackage, localArtifacts) => {
    try {
      require.resolve(specifier)
    } catch (resolveError) {
      if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
        throw resolveError
      }
      if (isPackage) {
        try {
          require.resolve(specifier + '/package.json')
        } catch (packageError) {
          if (packageError && packageError.code === 'MODULE_NOT_FOUND') {
            return resolveError
          }
          // An exports restriction proves the package exists even when its
          // package.json is not public. Preserve the root resolution failure.
          throw resolveError
        }
        // The package exists but its main/export target is broken.
        throw resolveError
      }
      return resolveError
    }
    if (localArtifacts) {
      let artifactError = null
      for (let i = 0; i < localArtifacts.length; i++) {
        try {
          require.resolve(localArtifacts[i])
          return null
        } catch (resolveError) {
          if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
            throw resolveError
          }
          artifactError = resolveError
        }
      }
      return artifactError
    }
    return null
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === 'wasm32-wasi')) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('./codechat-editor-client.wasi.cjs', false, ['./codechat-editor-client.wasm32-wasi.debug.wasm', './codechat-editor-client.wasm32-wasi.wasm'])
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        __dbgAttempt('WASI local artifact', './codechat-editor-client.wasi.cjs')
        wasiBinding = __dbgOk(
          './codechat-editor-client.wasi.cjs',
          require('./codechat-editor-client.wasi.cjs'),
        )
        nativeBinding = wasiBinding
        __napiLoadedBindingTarget = 'wasm32-wasi'
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === 'wasm32-wasi')) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('codechat-editor-client-wasm32-wasi', true, undefined)
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        if (process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          const bindingPackageVersion = require('codechat-editor-client-wasm32-wasi/package.json').version
          if (bindingPackageVersion !== '0.2.5') {
            throw new Error(`WASI binding package version mismatch, expected 0.2.5 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
        }
        __dbgAttempt('WASI package', 'codechat-editor-client-wasm32-wasi')
        wasiBinding = __dbgOk(
          'codechat-editor-client-wasm32-wasi',
          require('codechat-editor-client-wasm32-wasi'),
        )
        nativeBinding = wasiBinding
        __napiLoadedBindingTarget = 'wasm32-wasi'
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (
    !wasiBindingLoaded &&
    forceWasi &&
    !forceWasiError &&
    !__napiWasiFlavorRequested
  ) {
    __dbg('WASI was preferred but not found; retrying the native chain')
    nativeBinding = requireNative()
  }
  if ((forceWasiError || __napiWasiFlavorRequested) && !wasiBindingLoaded) {
    const error = new Error(
      __napiWasiFlavorRequested
        ? 'WASI binding for flavor "' + __napiWasiFlavor + '" not found'
        : 'WASI binding not found and NAPI_RS_FORCE_WASI is set to error',
    )
    __dbgChain('WASI load failed', wasiBindingErrors)
    __dbg(`THROWING: ${error.message}`)
    error.cause = createLoadErrorChain(wasiBindingErrors)
    throw error
  }
}

__dbg(
  `binding resolution finished: ${nativeBinding ? 'SUCCESS' : 'FAILURE'}, target=${__napiLoadedBindingTarget}`,
)
if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
    )
    // assign instead of the `new Error(message, { cause })` options form,
    // which Node < 16.9 silently ignores
    __dbgChain('every load attempt failed', loadErrors)
    __dbg(`THROWING: ${error.message}`)
    error.cause = createLoadErrorChain(loadErrors)
    throw error
  }
  __dbg('THROWING: Failed to load native binding, with no attempt recorded')
  throw new Error(`Failed to load native binding`)
}

function __napiStampBindingTarget(exportsObject, target) {
  if (
    Object.prototype.hasOwnProperty.call(exportsObject, '__napiBindingTarget')
  ) {
    if (exportsObject.__napiBindingTarget === target) {
      // Already ours: the root entry aliases the object it loaded, so a WASI
      // fallback candidate — or a `NAPI_RS_NATIVE_LIBRARY_PATH` override that
      // is a generated loader — arrives already stamped with this same value.
      return target
    }
    const error = new Error(
      '`__napiBindingTarget` is reserved by the generated binding loader, but the loaded binding already exports it. Rename the export, e.g. #[napi(js_name = "...")].',
    )
    error.code = 'ERR_NAPI_BINDING_TARGET_CONFLICT'
    throw error
  }
  if (!Object.isExtensible(exportsObject)) {
    // A `#[napi(module_exports)]` hook may seal or freeze this object
    // (`Object::seal` / `Object::freeze`). Reporting the artifact is metadata,
    // never a reason to fail an otherwise successful load, so the stamp is
    // skipped. What a consumer still sees then follows the entry point: the
    // browser and deferred loaders declare `__napiBindingTarget` at module
    // level and go on reporting it, while the CommonJS entries hand back this
    // very object as `module.exports`, so there the value is absent.
    return target
  }
  try {
    // [[Define]], not [[Set]]: an ordinary assignment walks the prototype
    // chain, so an inherited accessor could swallow the value or throw and
    // fail an otherwise successful load. The descriptor is what a successful
    // assignment would have produced.
    Object.defineProperty(exportsObject, '__napiBindingTarget', {
      configurable: true,
      enumerable: true,
      value: target,
      writable: true,
    })
  } catch {
    // Same rule as the non-extensible skip above: reporting the artifact is
    // metadata, never a reason to fail an otherwise successful load. An exotic
    // object (a Proxy whose defineProperty trap refuses) is skipped, not
    // thrown over.
  }
  // The CommonJS loaders assign this return value so `cjs-module-lexer` — and
  // therefore Node's CJS -> ESM named export detection — can see
  // `__napiBindingTarget` statically.
  return target
}
// Stamp before the alias, not after. The guard only reads `nativeBinding`
// (`hasOwnProperty` plus a comparison), which is safe against any addon
// accessor; an assignment is not, because a `#[napi(module_exports)]` hook can
// expose a getter reporting this very value and a setter that throws. So the
// assignment lands on the loader's own `module.exports`, still the original
// object here, and the alias below replaces it.
//
// The assignment is what keeps the marker a statically visible CommonJS export:
// `cjs-module-lexer` is Node's CJS -> ESM named export detection, it cannot see
// a bare call, and the later `module.exports = nativeBinding` does not undo the
// detection. The assignment itself always succeeds — its target is this
// loader's own, still extensible `module.exports` — and the alias below then
// discards the value it wrote. What a consumer reads is whatever the guard put
// on `nativeBinding`, so on a frozen binding, where the guard skips, the
// linked import resolves to `undefined`.
module.exports.__napiBindingTarget = __napiStampBindingTarget(nativeBinding, __napiLoadedBindingTarget)
module.exports = nativeBinding
module.exports.CodeChatEditorServer = nativeBinding.CodeChatEditorServer
module.exports.initServer = nativeBinding.initServer

__dbg(
  `exports check: CodeChatEditorServer=${typeof nativeBinding.CodeChatEditorServer} initServer=${typeof nativeBinding.initServer}`,
)
__dbg('==== binding load finished ====')
